### ISSUE TITLE
Outline is not showing up

### ISSUE THREAD

**Issue by alice4book** [Robinseibold/Unity-URP-Outlines#13]
As many before, I have a problem with outlines not showing up. I don't know what is causing this, I'm new to shaders. I did everything from readme and other issues with a similar problem.
This is how it looks: 
![image](https://user-images.githubusercontent.com/73715550/200410573-33d69d92-e61b-440c-9e85-64b5cc3cd3d1.png)

And this is how I setup materials:
![image](https://user-images.githubusercontent.com/73715550/200410703-5c909189-8b21-417f-9afc-8f054e5b10f6.png)

I'm gonna show what I have already done:
Add files to your project
![image](https://user-images.githubusercontent.com/73715550/200409496-77a82a49-6682-4057-9897-89fb063a7849.png)

Enable depth texture in the Universal Render Pipeline Asset
![image](https://user-images.githubusercontent.com/73715550/200409617-f65a8076-3863-4714-8481-5c00cef7bbad.png)

Add the 'Screen Space Outlines' renderer feature to the Universal Renderer Data
Adjust 'Screen Space Outlines' settings
I didn't change much, except those Outline Layers
![image](https://user-images.githubusercontent.com/73715550/200409772-d2ec9f57-d81c-41d2-8111-1932add21804.png)

Go to Project Settings > Graphics and add the 3 new ones (Outlines, UnlitColor, and ViewSpaceNormals) to the list of Always Included Shaders. 
![image](https://user-images.githubusercontent.com/73715550/200410078-05d1e92f-84bb-4ddb-bd1b-263d61c02434.png)

Thanks in advance

**Comment by zephyo** [comment]
You are missing several settings. Depth Priming Mode should be Auto or Forced, for one. Read https://github.com/Robinseibold/Unity-URP-Outlines/issues/10

**Comment by Robinseibold** [comment]
Thanks @zephyo. Did it work @alice4book? Can I close this issue?
