### ISSUE TITLE
Nothing seems to happen when feature added

### ISSUE THREAD

**Issue by kujo87** [Robinseibold/Unity-URP-Outlines#2]
Hi,

I've followed the readme (and watched through the video), but when adding this onto my scene, nothing happens. I've run the debugger on it, and it seems that all the appropriate stuff is being hit with breakpoints, but still get nothing.

I've marked Depth Texture on the render settings - anything else I could have missed?

**Comment by mamm0n** [comment]
@kujo87 Can you try changing **Render Pass Event** to **After Rendering Opaques** on Universal Renderer Data?

**Comment by kujo87** [comment]
@mamm0n  - ah - the background colour had alpha off - doing your change and setting the alpha correctly gives me an outline!

Thanks for the help

**Comment by mamm0n** [comment]
@kujo87 I'm glad you could handle it.
