### ISSUE TITLE
Antialiasing on "URP asset" forbid to use multiple SceenSpaceOutline

### ISSUE THREAD

**Issue by FomaFomitch** [Robinseibold/Unity-URP-Outlines#8]
Hello,

I want to use multiple screen space oulines. One black and another blue pale on different layers.
But when "MSAA antialiasing" is more than "none" on URP asset, only one of them works. Never in the same time.

![image](https://user-images.githubusercontent.com/74829959/180242151-c2c6844f-e53b-4af4-b3f1-4b61ead27e9e.png)

![image](https://user-images.githubusercontent.com/74829959/180243215-c4370ec3-4858-4e6a-be69-210a7690359b.png)

**Comment by OwenProto** [comment]
It's right under "known issues" in the readme that the outlines are incompatible with MSAA

**Comment by FomaFomitch** [comment]
Ok thanks my bad !
