### ISSUE TITLE
Does not work in build

### ISSUE THREAD

**Issue by OwenMagelssen** [Robinseibold/Unity-URP-Outlines#9]
In a build, only UI will render when using a renderer asset that has this render feature (tested with screen space overlay UI). Of note: to get the effect working to begin with, I had to apply the fix mentioned in issue #1 (changing order to "after opaques").

URP 12.1.7
2021 LTS

**Comment by Sid2003073** [comment]
I have the same issue. 
Mine is an Android build. Are you guys also building for Android?

Maybe the package is not supported for Android.

**Comment by jgthibodeau** [comment]
> I have the same issue. Mine is an Android build. Are you guys also building for Android?
> 
> Maybe the package is not supported for Android.

WebGl here.

**Comment by OwenMagelssen** [comment]
I was building for Windows

**Comment by UnscriptedLogic** [comment]
My windows build doesn't move past the splash screen for me,

**Comment by victorytoad43** [comment]
Hey friends, I was having this exact issue. The errors are a result of the newly added 'Hidden' shaders not being included in the build, as they're hidden and never referenced in the scene

Go to Project Settings > Graphics and add the 3 new ones (Outlines, UnlitColor, and ViewSpaceNormals) to the list of Always Included Shaders. This made my build function as expected

**Comment by antonsem** [comment]
Can confirm that @victorytoad43's solution works! Thank you!

**Comment by Robinseibold** [comment]
Thank you @victorytoad43! should probably be added to the README.
